### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [K144U/quantm-codes#1]
I recently came across your project quantm-codes and I noticed that the repository github.com/K144U/quantm-codes currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by K144U** [comment]
> I recently came across your project quantm-codes and I noticed that the repository github.com/K144U/quantm-codes currently does not have a license specified.
> 
> Why Adding a License is Important?
> 
> As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
> 
> > Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.
> 
> Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.
> 
> Thanks!

Thank you for bringing this to my attention! You're absolutely right—having a license is essential for ensuring that others can use, modify, and distribute the project under clear terms. I'll look into adding an appropriate open-source license, and Apache 2.0 seems like a great suggestion. I'll update the repository soon with a valid license.

Thanks again for your feedback and for taking the time to improve the project!

**Comment by K144U** [comment]
This might sound stupid .... but 
A few days ago, I was considering building a single neuron on a quantum computer. Could you kindly provide some guidance or suggestions?

**Comment by cbjuan** [comment]
Thank you! 

About your question. The Qiskit Textbook was a great resource to learn about NNs & Quantum. https://github.com/qiskit-community/qiskit-textbook/tree/main/content/ch-machine-learning

Also, I invite you to check out the IBM Quantum learning platform https://learning.quantum.ibm.com/
